
class ace_advanced_throwing_enablePickUp TURN_ON;
class ace_advanced_throwing_enablePickUpAttached TURN_ON;


class ace_advanced_throwing_enable TURN_ON;
class ace_advanced_throwing_showThrowArc TURN_OFF;
class ace_advanced_throwing_showMouseControls TURN_ON;
