
class ace_switchunits_enableSwitchUnits TURN_OFF;
class ace_switchunits_switchToWest TURN_OFF;
class ace_switchunits_switchToEast TURN_OFF;
class ace_switchunits_switchToIndependent TURN_OFF;
class ace_switchunits_switchToCivilian TURN_OFF;
class ace_switchunits_enableSafeZone TURN_ON;
class ace_switchunits_safeZoneRadius SET_VAL(100);
