branches:
  only:
   - master
   - develop
language: python
python:
- '3.4'
before_install:
- sudo add-apt-repository ppa:koffeinflummi/armake -y
- sudo apt-get update -qq
- sudo apt-get install armake -y
install: true
before_script:
- if [ -n "${GH_TOKEN}" ] && [ "${TRAVIS_BRANCH}" == "master" ] && [ "${TRAVIS_PULL_REQUEST}" == "false" ]; then
    pip install pygithub;
    pip install pygithub3;
    pip install colorama;
  fi
script:
- python3 tools/validator_cfg.py
- python3 tools/validator_sqf.py
- python3 tools/validator_xml.py
- python3 tools/createmissions.py

notifications:
  email:
    on_success: never
    on_failure: change
