branches:
  only:
   - master
   - develop
language: python
python:
- '3.4'
before_script:
- if [ -n "${GH_TOKEN}" ] && [ "${TRAVIS_BRANCH}" == "master" ] && [ "${TRAVIS_PULL_REQUEST}" == "false" ]; then
    pip install pygithub;
    pip install pygithub3;
  fi
script:
- python3 tools/sqf_validator.py
- python3 tools/config_style_checker.py

notifications:
  email:
    on_success: never
    on_failure: change
