version: 2
jobs:
  build:
    docker:
      - image: acemod/armake
    steps:
      - checkout
      - run:
          name: Validate cfg
          command: python3 tools/validator_cfg.py
      - run:
          name: Validate sqf
          command: python3 tools/validator_sqf.py
      - run:
          name: Validate xml
          command: python3 tools/validator_xml.py
      - run:
          name: Build
          command: armake --version
      - deploy:
          name: Update documentation and translation statistics
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ] && [ "${CIRCLE_PROJECT_USERNAME}" == "Brig13Team" ]; then
              pip install pygithub pygithub3
              python3 tools/releasebuild.py
            else
              echo "Skipping, not on Brig13Team/Operation_Kerberos master branch..."
            fi
