#include "config\dialogMacros.hpp"
#include "inc\definecommongrids.inc"
#include "config\defineRALColors.hpp"
#include "config\defineGrids.hpp"
#include "config\defineResColors.hpp"
#include "config\defineResIncl.hpp"
#include "config\defineResCommon.hpp"
