/*
 * TRANSLATION FILE (ENGLIGH)
 * 
 * Alternative to stringtable.csv which is simpler to install for the mission maker.
 * The token ""%1"" represents a dynamic value generated by the scripts, like a vehicle name.
 * 
 * Alternative au stringtable.csv qui est plus simple à installer pour le créateur de mission.
 * Le mot-clé ""%1"" représente une valeur dynamique fournie par les scripts, comme par exemple un nom de véhicule.
 */

STR_R3F_LOG_action_heliporter = "Objekt anheben";
STR_R3F_LOG_action_heliporter_fait = "Objekt zu ""%1"" angehängt.";
STR_R3F_LOG_action_heliport_larguer = "Objekt fallen lassen";
STR_R3F_LOG_action_heliport_larguer_fait = "Objekt zu ""%1"" fallen gelassen.";
STR_R3F_LOG_action_heliport_attente = "Anhängen... (%1)";
STR_R3F_LOG_action_heliport_echec_attente = "Anheben abgebrochen ! Bleib während des Anhängens am Schweben.";

STR_R3F_LOG_action_deplacer_objet = "Nimm ""%1""";
STR_R3F_LOG_action_relacher_objet = "Lass ""%1"" los.";
STR_R3F_LOG_action_aligner_pente = "Dem Hang anpassen";
STR_R3F_LOG_action_aligner_sol = "Dem Boden anpassen";
STR_R3F_LOG_action_aligner_horizon = "Horizontal ausrichten";
STR_R3F_LOG_action_tourner = "Schwenken nach links/rechts (X / C keys)";
STR_R3F_LOG_action_rapprocher = "Näher/Weiter (F / R keys)";
STR_R3F_LOG_ne_pas_monter_dans_vehicule = "Du kannst in kein Fahrzeug einsteigen, während du das Objekt trägst !";

STR_R3F_LOG_action_charger_deplace = "In Fahrzeug einladen";
STR_R3F_LOG_action_selectionner_objet_charge = "Lade ""%1"" in...";
STR_R3F_LOG_action_charger_selection = "... in ""%1"" einladen";
STR_R3F_LOG_action_selectionner_objet_fait = "Wähle den Zielpunkt für ""%1""...";
STR_R3F_LOG_action_charger_en_cours = "Es wird geladen...";
STR_R3F_LOG_action_charger_fait = "Das Objekt ""%1"" wurde in ""%2"" eingeladen.";
STR_R3F_LOG_action_charger_pas_assez_de_place = "Im Fahrzeug ist nicht genug Platz für das Objekt !";

STR_R3F_LOG_action_remorquer_direct = "Ziehe ""%1""";
STR_R3F_LOG_action_remorquer_deplace = "Das Objekt ankoppeln";
STR_R3F_LOG_action_detacher = "Das Objekt abkoppeln";
STR_R3F_LOG_action_detacher_fait = "Objekt abgekoppelt.";
STR_R3F_LOG_action_detacher_impossible_pour_ce_vehicule = "Nur der Pilot kann das Fahrzeug abhängen.";

STR_R3F_LOG_action_contenu_vehicule = "Fahrzeuginhalt ansehen";
STR_R3F_LOG_action_decharger_en_cours = "Entladen in Arbeit...";
STR_R3F_LOG_action_decharger_fait = "Das Objekt ""%1"" wurde entladen.";
STR_R3F_LOG_action_decharger_deja_fait = "Das Objekt wurde bereits entladen !";
STR_R3F_LOG_action_decharger_deplacable_exceptionnel = "Wenn das Objekt losgelassen wurde lässt es sich nicht mehr manuell bewegen.<br/>Willst du das wirklich ?";

STR_R3F_LOG_action_ouvrir_usine = "Öffne die Fabrik";
STR_R3F_LOG_action_creer_en_cours = "Es wird gebaut...";
STR_R3F_LOG_action_creer_fait = "Das Objekt ""%1"" wurde gebaut.";
STR_R3F_LOG_action_creer_pas_assez_credits = "Die Fabrik hat nicht genug Ressourcen für den Bau.";
STR_R3F_LOG_action_revendre_usine_direct = """%1"" zurück in die Fabrik schicken";
STR_R3F_LOG_action_revendre_usine_deplace = "Zurück in die Fabrik schicken";
STR_R3F_LOG_action_revendre_usine_selection = "... zurück in die Fabrik schicken";
STR_R3F_LOG_action_revendre_en_cours = "Beim zurück in die Fabrik schicken...";
STR_R3F_LOG_action_revendre_fait = "Das Objekt ""%1"" wurde in die Fabrik zurück geschickt.";
STR_R3F_LOG_action_revendre_decharger_avant = "Du kannst kein Objekt zurückschicken, während sich Ladung im Innern befindet !";

STR_R3F_LOG_mutex_action_en_cours = "Die aktuelle gabe ist nicht beendet !";
STR_R3F_LOG_joueur_dans_objet = "Es befindet sich ein Spieler in ""%1"" !";
STR_R3F_LOG_objet_en_cours_transport = "Das Objekt ""%1"" ist bereits im Verlagern !";
STR_R3F_LOG_objet_remorque_en_cours = "Unmöglich, da ""%1"" ein anderes Objekt zieht !";
STR_R3F_LOG_trop_loin = "Unmöglich, das Objekt ""%1"" ist zu weit entfernt !";

STR_R3F_LOG_dlg_CV_titre = "Fahrzeuginhalt";
STR_R3F_LOG_dlg_CV_capacite_vehicule = "Ladung : %1/%2";
STR_R3F_LOG_dlg_CV_btn_decharger = "ENTLADEN";
STR_R3F_LOG_dlg_CV_btn_fermer = "ABBRECHEN";

STR_R3F_LOG_dlg_LO_titre = "Fabrik";
STR_R3F_LOG_dlg_LO_credits_restants = "Verbleibende Ressourcen : %1";
STR_R3F_LOG_dlg_LO_btn_creer = "BAUEN";
STR_R3F_LOG_dlg_LO_btn_fermer = "ABBRECHEN";

STR_R3F_LOG_nom_fonctionnalite_proprietes = "Eigenschaften";
STR_R3F_LOG_nom_fonctionnalite_side = "Seite";
STR_R3F_LOG_nom_fonctionnalite_places = "Sitzplätze";
STR_R3F_LOG_nom_fonctionnalite_passif = "Es ist :";
STR_R3F_LOG_nom_fonctionnalite_passif_deplace = "vom Spieler bewegbar";
STR_R3F_LOG_nom_fonctionnalite_passif_heliporte = "an Helikopter angehängbar";
STR_R3F_LOG_nom_fonctionnalite_passif_remorque = "abschleppbar";
STR_R3F_LOG_nom_fonctionnalite_passif_transporte = "transportierbar";
STR_R3F_LOG_nom_fonctionnalite_passif_transporte_capacite = "Ladungskosten %1";
STR_R3F_LOG_nom_fonctionnalite_actif = "Es hat die Fähigkeiten :";
STR_R3F_LOG_nom_fonctionnalite_actif_heliporte = "an Helikopter anhängen";
STR_R3F_LOG_nom_fonctionnalite_actif_remorque = "abschleppen";
STR_R3F_LOG_nom_fonctionnalite_actif_transporte = "transportieren";
STR_R3F_LOG_nom_fonctionnalite_actif_transporte_capacite = "Transportkapazität %1";

STR_R3F_LOG_deverrouillage_en_cours = "Aufbrechen... (%1)";
STR_R3F_LOG_deverrouillage_echec_attente = "Aufbrechen abgebrochen ! Behalte das Ziel anvisiert, während du es aufbrichst.";
STR_R3F_LOG_deverrouillage_succes_attente = "Objekt aufgebrochen.";
STR_R3F_LOG_action_deverrouiller = "Breche ""%1"" auf";
STR_R3F_LOG_action_deverrouiller_impossible = "Objekt abgeschlossen";