PREP(handleRescuePoint);

PREPS(mainmission,capture);
PREPS(mainmission,device);
PREPS(mainmission,dronecommando);
PREPS(mainmission,emp);
PREPS(mainmission,hold);
PREPS(mainmission,hostage);
PREPS(mainmission,intel);
PREPS(mainmission,jammer);
PREPS(mainmission,prototype);
PREPS(mainmission,radiotower);
PREPS(mainmission,scarab);
PREPS(mainmission,scarab_failed);
PREPS(mainmission,upload);
PREPS(mainmission,weaponcache);

PREPS(sidemission,airsuperiority);
PREPS(sidemission,artillery);
PREPS(sidemission,chopper);
PREPS(sidemission,chopper_failed);
PREPS(sidemission,radar);
PREPS(sidemission,supplys_succeeded);
PREPS(sidemission,wreck);

PREPS(spawn,chooseLocation);
PREPS(spawn,chooseMission);
PREPS(spawn,createAtRescuePoint);
PREPS(spawn,getAmount);
PREPS(spawn,getObjects);
PREPS(spawn,getRadius);
PREPS(spawn,spawnTargets);

PREPS(spawnfunctions,airsuperiority);
PREPS(spawnfunctions,minefield);
PREPS(spawnfunctions,supplys);

PREPS(statemachine,addMain);
PREPS(statemachine,addSide);
PREPS(statemachine,addTask);
PREPS(statemachine,cancelALL);
PREPS(statemachine,checkCounter);
PREPS(statemachine,checkClear);
PREPS(statemachine,checkOneCounter);
PREPS(statemachine,checkTwoCounter);
PREPS(statemachine,cleanup);
PREPS(statemachine,decreaseCounter);
PREPS(statemachine,endmission);
PREPS(statemachine,getMissions);
PREPS(statemachine,HoldPFH);
PREPS(statemachine,increaseCounter);
PREPS(statemachine,initHold);
PREPS(statemachine,initcounter);
PREPS(statemachine,initOneCounter);
PREPS(statemachine,initTwoCounter);
PREPS(statemachine,isActiveMission);
PREPS(statemachine,onTransition);
PREPS(statemachine,rtb);
PREPS(statemachine,spawn);
