theme: jekyll-theme-slate
title: Operation Kerberos
description: Operation Kerberos is a dynamic Arma 3 mission.</br>It dynamicaly generates random objectives, which have to be completed by human players. The mission forces the players to play together as a team to achive success.
show_downloads: false
